import type { Metadata } from 'next'
import './globals.css'

import { eUkraine, eUkrainehead, geistMono, geistSans, manrope } from '@/app/ui/fonts'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='uk'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${eUkrainehead.variable} ${manrope.variable} ${eUkraine.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	)
}
