import type { Metadata } from "next"

import './globals.css'

import { eUkraine, eUkrainehead, geistMono, geistSans, manrope, sacramento } from '@/app/ui/fonts'

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="uk"
			className={`${geistSans.variable} ${geistMono.variable} ${eUkrainehead.variable} ${manrope.variable} ${eUkraine.variable} ${sacramento.variable} antialiased`}
		>
			<body className="font-manrope">{children}</body>
		</html>
	);
}
